config/routes.rb
Rails.application.routes.draw do
  resources :languages
  resources :countries
  resources :genders
  resources :customers

  resources :products do
    collection do
      post 'search'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :country
  belongs_to :language
  belongs_to :gender


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:gender_id, :title, :name, :pre_name, :street, :additional_line, :zip_code, :string, :city, :country_id, :language_id, :phone_number, :cell_phone_number, :email, :birthday)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gender_id %><br>
    <%= f.number_field :gender_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pre_name %><br>
    <%= f.text_field :pre_name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :additional_line %><br>
    <%= f.text_field :additional_line %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.number_field :country_id %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br>
    <%= f.number_field :language_id %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :cell_phone_number %><br>
    <%= f.text_field :cell_phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Gender</th>
      <th>Title</th>
      <th>Name</th>
      <th>Pre name</th>
      <th>Street</th>
      <th>Additional line</th>
      <th>Zip code</th>
      <th>String</th>
      <th>City</th>
      <th>Country</th>
      <th>Language</th>
      <th>Phone number</th>
      <th>Cell phone number</th>
      <th>Email</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.gender_id %></td>
        <td><%= customer.title %></td>
        <td><%= customer.name %></td>
        <td><%= customer.pre_name %></td>
        <td><%= customer.street %></td>
        <td><%= customer.additional_line %></td>
        <td><%= customer.zip_code %></td>
        <td><%= customer.string %></td>
        <td><%= customer.city %></td>
        <td><%= customer.country_id %></td>
        <td><%= customer.language_id %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.cell_phone_number %></td>
        <td><%= customer.email %></td>
        <td><%= customer.birthday %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gender:</strong>
  <%= @customer.gender_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @customer.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Pre name:</strong>
  <%= @customer.pre_name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Additional line:</strong>
  <%= @customer.additional_line %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @customer.zip_code %>
</p>

<p>
  <strong>String:</strong>
  <%= @customer.string %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @customer.language_id %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<p>
  <strong>Cell phone number:</strong>
  <%= @customer.cell_phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @customer.birthday %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>